# SPDX-FileCopyrightText: 2021-2025 DINUM <floss@numerique.gouv.fr>
# SPDX-FileCopyrightText: 2024-2025 Université Grenoble Alpes
# SPDX-License-Identifier: MIT

services:
  api:
    depends_on:
      - postgres
    build:
      context: "."
      dockerfile: Dockerfile.api
    env_file: .env
    restart: unless-stopped
    command: yarn start

  update:
    depends_on:
      - api
      - postgres
    build:
      context: "."
      dockerfile: Dockerfile.api
    env_file: .env
    restart: always
    # runs every 4 hours (240 minutes)
    command: yarn update-then-wait 240

  web:
    depends_on:
      - api
    build:
      context: "."
      dockerfile: Dockerfile.web
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - api
      - web
    restart: unless-stopped

  postgres:
    image: postgres:16
    shm_size: 256m
    environment:
      POSTGRES_LOG_STATEMENTS: all
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker-data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
