version: "3.8"
services:
  api:
    platform: linux/amd64
    image: codegouvfr/api
    env_file: .env
    restart: unless-stopped

  web:
    platform: linux/amd64
    image: codegouvfr/web
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
      - web
    restart: unless-stopped
