version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile
      target: api
    env_file: .env
    restart: unless-stopped

  web:
    build:
      context: "."
      dockerfile: Dockerfile
      target: web
    environment:
      PUBLIC_URL: "/sill-docker-compose"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - api
      - web
    restart: unless-stopped
