version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile
      target: api
    env_file: .env
    restart: unless-stopped

  web:
    build:
      context: "."
      dockerfile: Dockerfile
      target: web
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "4000:80" # Map port 80 on the host to port 80 in the NGINX container
    volumes:
      - ./nginx/etc/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - api
      - web
    restart: unless-stopped
