version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: Dockerfile
      target: api
    env_file: .env
    restart: unless-stopped

  web:
    build:
      context: "."
      dockerfile: Dockerfile
      target: web
    restart: unless-stopped
