api:
  image:
    tag: "latest"
    pullPolicy: IfNotPresent
  env:
    OIDC_ISSUER_URI: "https://auth.code.gouv.fr/auth/realms/codegouv"
    OIDC_CLIENT_ID: "sill"

update:
  image:
    tag: "latest"
    pullPolicy: IfNotPresent

ingress:
  enabled: false

database:
  password: "change-this-in-production"

postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    username: "catalogi_user"
    password: "change-this-in-production"
    database: "catalogi_db"

# Web container configuration
web:
  replicaCount: 1
  image:
    repository: codegouvfr/catalogi-web
    tag: "latest"
    pullPolicy: IfNotPresent
  customNginxConfig: |
    server {
        listen 8080;
        
        gzip on; 
        gzip_vary on; 
        gzip_min_length 1024; 
        gzip_proxied expired no-cache no-store private auth; 
        gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/javascript application/xml; 
        gzip_disable "MSIE [1-6]\.";

        # Add comprehensive CSP for Vite dynamic imports  
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://auth.code.gouv.fr; frame-src 'self' https://auth.code.gouv.fr; object-src 'none';" always;

        root /usr/share/nginx/html;
        index index.html;      

        # Static assets with caching
        location ~* \.(js|css|woff2?|eot|ttf|xml|md)$ {
          try_files $uri =404;
          expires 1y;
          access_log off;
          add_header Cache-Control "public";
        }

        # Images and other assets  
        location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
          try_files $uri =404;
          expires 1y;
          add_header Cache-Control "public";
        }

        # HTML, JSON, TXT files
        location ~* \.(html|json|txt)$ {
          try_files $uri =404;
          expires -1;
        }

        # SPA fallback for everything else (routes)
        location / {
          try_files $uri $uri/ /index.html;
        }
    }
