version: "3.8"
services:
  api:
    platform: linux/amd64
    image: codegouvfr/sill-api:1.42.7
    env_file: .env
    restart: unless-stopped

  web:
    platform: linux/amd64
    image: codegouvfr/sill-web:1.42.54
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - api
      - web
    restart: unless-stopped
