{{- if .Values.adminer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalogi.fullname" . }}-adminer
  labels:
    {{- include "catalogi.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "catalogi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: adminer
{{- end }}