{{- if .Values.adminer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalogi.fullname" . }}-adminer
  labels:
    {{- include "catalogi.labels" . | nindent 4 }}
    app.kubernetes.io/component: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "catalogi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: adminer
  template:
    metadata:
      labels:
        {{- include "catalogi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: adminer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "catalogi.serviceAccountName" . }}
      containers:
        - name: adminer
          image: "{{ .Values.adminer.image.repository }}:{{ .Values.adminer.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
{{- end }}