apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalogi.fullname" . }}-api
  labels:
    {{- include "catalogi.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "catalogi.api.selectorLabels" . | nindent 4 }}