{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalogi.fullname" . }}-database
  labels:
    {{- include "catalogi.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "catalogi.databaseUrl" . | b64enc | quote }}
  database-password: {{ .Values.database.password | b64enc | quote }}
{{- end }}