apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalogi.fullname" . }}-web
  labels:
    {{- include "catalogi.web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "catalogi.web.selectorLabels" . | nindent 4 }}